---
title: "Student Performance"
description: |
  The success of a student relies on many different factors; knowing how to 
  handle and control these factors will increase a students performance.
site: distill::distill_website
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggthemes)
```

```{r}
student<- read.csv("StudentsPerformance.csv")
student|> 
select(parental.level.of.education, math.score, writing.score, reading.score, gender, race.ethnicity)|> 
ggplot(mapping = aes(y = parental.level.of.education, x = reading.score, color = gender))+
  geom_point(alpha = 0.3, size = 5) + 
  facet_wrap(~race.ethnicity)+ 
  theme_calc()+
  labs(title = "Reading Scores", subtitle = "Cluster of higher scores can be observed for all race groups with a parental 
level of education = Associates Degree", x = "Reading Scores", y = "Parental Level of Education", caption = "Kaggle: JAKKI SESHAPANPU 2018")

```
```{r}
student<- read.csv("StudentsPerformance.csv")
student|> 
select(parental.level.of.education, math.score, writing.score, reading.score, gender, race.ethnicity)|> 
ggplot(mapping = aes(y = parental.level.of.education, x = math.score, color = gender))+
  geom_point(alpha = 0.3, size = 5) + 
  facet_wrap(~race.ethnicity)+ 
  theme_calc()+
  labs(title = "Math Scores", subtitle = "Male students have higher scores.", x = "Math Scores", y = "Parental Level of Education", caption = "Kaggle: JAKKI SESHAPANPU 2018")
```
```{r}
student<- read.csv("StudentsPerformance.csv")
student|> 
select(parental.level.of.education, math.score, writing.score, lunch, reading.score, gender, race.ethnicity)|> 
ggplot(mapping = aes(y = parental.level.of.education, x = writing.score, color = gender))+
  geom_point(alpha = 0.3, size = 5) + 
  facet_wrap(~race.ethnicity) +
  theme_calc()+
  labs(title = "Writing Scores", subtitle = "Group C and D have a mostly tight range, whereas many outliers are noticable in other ethnic groups.", x = "Writing Scores", y = "Parental Level of Education", caption = "Kaggle: JAKKI SESHAPANPU 2018")
```

