---
title: "Effects of Lunch on Student Performance"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggthemes)
```
## Plot 1
```{r}
student<- read.csv("StudentsPerformance.csv")
student|> 
select(lunch, math.score, writing.score, reading.score, gender, race.ethnicity)|> 
ggplot(mapping = aes(y = lunch, x = reading.score))+ 
  geom_boxplot(alpha = 0.5, color = "brown1", size = 2)+ 
  facet_wrap(~gender)+ 
  theme_calc()+
  labs(title = "Lunch Type vs Reading Score", subtitle = "Higher score quartile for both male and female students recieving a standard lunch.", x = "Reading Scores", y = "Lunch Type", caption = "Kaggle: JAKKI SESHAPANPU 2018")
```

## Plot 2
```{r}
student<- read.csv("StudentsPerformance.csv")
student|> 
select(lunch, math.score, writing.score, reading.score, gender, race.ethnicity)|> 
ggplot(mapping = aes(y = lunch, x = writing.score))+ 
  geom_boxplot(alpha = 0.5, color = "brown1", size = 2)+ 
  facet_wrap(~gender)+ 
  theme_calc()+
  labs(title = "Lunch Type vs Writing Score", subtitle = "Higher writing scores can be observed for students with a standard lunch. ", x = "Writing Scores", y = "Lunch Type", caption = "Kaggle: JAKKI SESHAPANPU 2018")
```
## Plot 3  

```{r}
student<- read.csv("StudentsPerformance.csv")
student|> 
select(lunch, math.score, writing.score, reading.score, gender, race.ethnicity)|> 
ggplot(mapping = aes(y = lunch, x = math.score))+ 
  geom_boxplot(alpha = 0.5, color = "brown1", size = 2)+ 
  facet_wrap(~gender)+ 
  theme_calc()+
  labs(title = "Lunch Type vs Math Score", subtitle = "Higher writing scores can be observed for students with a standard lunch. ", x = "Math Scores", y = "Lunch Type", caption = "Kaggle: JAKKI SESHAPANPU 2018")
```


## **Summary**  

As visible in the plots above, the mean test score for all tests is higher than the mean test score for students recieving a free/reduced lunch. 

Based on previous studies, 
```

