---
title: "Reading Scores"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggthemes)
```

**1.**
```{r}
student<- read.csv("StudentsPerformance.csv")

student|> 
select(lunch,parental.level.of.education, math.score, writing.score, reading.score, gender, race.ethnicity)|> # select wanted columns
ggplot(mapping = aes(y = lunch, x = reading.score))+ # assign variables
  geom_boxplot(alpha = 0.5, color = "brown1", size = 1)+ # plot
  facet_wrap(~gender)+ # separate by gender
  theme_calc()+ # add preferred theme
  theme(panel.background = element_rect(fill = "azure2")) + # add background color to plot
  labs(title = "Lunch Type vs Reading Score", subtitle = "Higher score quartile for both male and female students recieving a standard lunch.", x = "Reading Scores", y = "Lunch Type", caption = "Kaggle: JAKKI SESHAPANPU 2018") # add titles
```
**2.**
```{r}
student<- read.csv("StudentsPerformance.csv")

student|> 
select(parental.level.of.education, math.score, writing.score, reading.score, gender, race.ethnicity)|> # select wanted columns
ggplot(mapping = aes(y = parental.level.of.education, x = reading.score, color = gender))+ # assign variables
  geom_point(alpha = 0.3, size = 3) + # plot
  facet_wrap(~race.ethnicity) + # seperate by gender
  theme_calc()+ # add preferred theme
  labs(title = "Education and Race", subtitle = "Female students have higher scores in most ethnic groups.", x = "Reading Scores", y = "Parental Level of Education", caption = "Kaggle: JAKKI SESHAPANPU 2018") # add titles
```
**3.**
```{r}
student<- read.csv("StudentsPerformance.csv")

student|> 
select(parental.level.of.education, reading.score, gender, test.preparation.course)|> #select wanted columns
ggplot(mapping = aes( y = test.preparation.course, x = reading.score)) + # assign variables
  geom_boxplot() + # plot
facet_wrap(~gender) + # separate by gender
  theme_calc()+ # add preferred theme
  theme(panel.background = element_rect(fill = "azure2")) + # add background color to plto
  labs(title = "How Preparation Affects Test Scores", x = "Reading Scores", y = "Test Preparation Course", subtitle = "Female students have higher averages in both categories.", caption = "Kaggle: JAKKI SESHAPANPU 2018") # add titles
```

